# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# update_patch.py
# Created on: 2014-12-16 10:40:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os

# Parameters
update_list = arcpy.GetParameter(0)
scratch_workspace = arcpy.GetParameterAsText(1)
output_workspace = arcpy.GetParameterAsText(2)
output_shapefile = os.path.join(output_workspace, "patch_all.shp")
arcpy.AddMessage(output_shapefile)

# Loop through list of files
count = len(update_list)
i=1

for layer in update_list:
	if i==1:
		input_layer = layer
		i+=1
	elif i<count:
		update_layer = layer
		temp_name = "temp_" + str(i)
		temp_layer = os.path.join(scratch_workspace, temp_name)
		arcpy.Update_analysis(input_layer, update_layer, temp_layer, "BORDERS", "")
		arcpy.AddMessage(temp_name)
		input_layer = temp_layer
		i+=1
	else:
		update_layer = layer
		arcpy.Update_analysis(input_layer, update_layer, output_shapefile, "BORDERS", "")